import type { Metadata } from "next";
import { introduction, profile, site } from "@/content";

export const siteDescription = introduction.join(" ");
export const siteOgTitle = `${profile.nameKo} | ${profile.position}`;

/** The site-wide preview image generated by app/opengraph-image.tsx. */
const shareImage = { url: "/opengraph-image", width: 1200, height: 630 };

/**
 * Canonical URL and link-preview tags for one page. Previews (KakaoTalk, Slack …) open og:url,
 * so every page points at itself — a shared page always opens that page.
 */
export function pageMetadata(path: string, page: { title?: string; description?: string } = {}): Metadata {
  const title = page.title ? `${page.title} | ${profile.nameKo}` : siteOgTitle;
  const description = page.description ?? siteDescription;
  return {
    ...(page.title && { title: page.title }),
    ...(page.description && { description: page.description }),
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "ko_KR",
      siteName: site.title,
      url: path,
      title,
      description,
      images: [shareImage],
    },
    twitter: { card: "summary_large_image", title, description, images: [shareImage] },
  };
}
