// Source: Notion "직무 및 이력 (Experiences)" — each company toggle and its nested project callouts.

import type { Experience } from "@/types/content";

export const experiences: Experience[] = [
  {
    role: "Head of Product Dev Team",
    company: "Studio XID (ProtoPie)",
    department: "Product Dev Team",
    tenure: "2026.01 - Present",
    mission: "Take design-to-code AI from PoC to official launch — completed with the ProtoPie MCP launch (2026.10)",
    projects: [
      {
        role: "Design & development (solo)",
        productLabel: "New product PoC",
        product: "[Decision Graph](/projects/decision-graph)",
        period: "2026.08 - 2026.10",
        title: "LLM pipeline for decision extraction",
        subtitle: "(Slack·Notion → decision records with evidence)",
        details: [
          "Turned PO requirements into a technical spec, then designed and built (solo) the LLM pipeline PoC that extracts who decided what and why from Slack and Notion, with source evidence",
          "Validated PoC results against a golden set where people manually marked the correct decisions on one real project — extracted 80%+ of the human-labeled decisions",
          "Verified and reviewed the feared technical risks firsthand through the PoC (judging quality against human-made ground truth, one-way records, preventing duplicate entries on re-runs)",
          "Chose the two-tier inference structure (first-pass classification: lightweight model; extraction and validation: high-capability model) by comparing options on the same tests (all-lightweight rejected after passing only 17 of 24)",
          "Logged time and cost per request to find bottlenecks and improved the call structure — on the same data, 74% fewer calls (1,289 → 336) and 25% lower cost ($10.2 → $7.6); re-running only the changed parts: $0.7",
          "Checked quality on every change with 24 test cases with known correct answers (with a cap on evaluation cost)",
        ],
      },
      {
        role: "Head of Product Dev Team",
        product: "[ProtoPie MCP](https://www.protopie.io/blog/protopie-mcp-official) (Dev View · Code MCP) official launch",
        period: "2026.01 - 2026.10",
        title: "AI-based code generation system",
        subtitle: "(PoC → productization)",
        details: [
          "[Hands-on] Designed the code generation pipeline combining rule-based modules with AI model stages, and developed the core pipeline (PoC)",
          "[Hands-on] Designed training for auxiliary models that understand images and layout (structure), and built training data",
          "[Hands-on] Designed the product integration architecture for plugging the code generation pipeline into the existing product (ProtoPie)",
          "[Team lead] Ran an agile team of 4–5 AI engineers and app developers — model training by the AI engineers, integration development with the team",
          "[Team lead] Designed the MLOps pipeline from data cleaning → training → deployment",
          "[Team lead] Expanded to AOS, iOS and Web cross-platform; official launch as ProtoPie MCP in October 2026 (Dev View · Code MCP, code generation for 7 frameworks)",
        ],
      },
    ],
  },
  {
    role: "Product Owner",
    company: "ESTsoft",
    department: "AI Agent Lab / Alan Development Team / PO",
    tenure: "2025.04 - 2026.01",
    mission: "Turn the research team's pilot service Alan into a paid commercial product — completed with the Pro subscription launch and first paid revenue",
    projects: [
      {
        role: "Product Owner",
        product: "Alan",
        period: "2025.04 - 2026.01",
        title: "AI search engine service (LLM-based agentic AI)",
        subtitle: "Advancing ’Alan’ (ESTsoft)",
        details: [
          "Led a service in trial operation at the research organization through commercial launch and monetization",
          "Led the development team for an LLM-based agentic AI app service, working as Product Owner",
          "Led a team made up of AI researchers and app developers (FE, BE)",
          "Operated and managed separate Dev, QA, Stage and Release servers",
          "Architected the Azure, Fast API, React and LangGraph structure",
          "Ran quality testing and collaborated with other in-house development, quality and infrastructure teams (QA, authentication, payments, infrastructure, etc.)",
          "Handled feature planning, scheduling and risk management for the LLM-based AI app service",
          "Built in-house image search, YouTube search & summarization, report generation and slide generation features plus specialized agents (led slide generation from research and planning onward)",
          "Set up the payment system process and the paid product policy",
          "Deployed the deep research and slide generation services, launched the Pro subscription, and developed an internal back-office operations tool",
          "Pro subscription brought the service's first paid revenue (figures not disclosed); building on it, planned an enterprise product (later the basis for institutional contract revenue)",
          "In commercial operation ([myalan.ai](https://myalan.ai/))",
        ],
      },
    ],
  },
  {
    // Grouped as one because the department moved between Tmax affiliates (newest affiliate first)
    company: "Tmax Group",
    tenure: "2017.01 - 2025.04",
    units: [
      {
        role: "Project Leader, Development Team",
        company: "TmaxMetaAI",
        department: "Meta AI Research Division / Researcher (Head of Office)",
        tenure: "2022.07 - 2025.04",
        projects: [
          {
            role: "Project Leader",
            product: "MX studio",
            period: "2022.07 - 2025.02",
            title: "Software for building 3D web components",
            subtitle: "Development of 'MX studio' and productization based on it",
            brief: [
              "Led the MX studio engine team and a task force (planning, design, development, QA)",
              "Led design/development of the physics engine, real-time rendering & post-processing, 3D events/actions and a node-based visual code system",
              "Productized Dr.Meta and Meta.CRO on its output; ran an external beta test",
            ],
            details: [
              "Led the MX studio engine team",
              "Led a task force team of planners, designers, developers and QA",
              "Led design/development of events and actions for 3D objects",
              "Led design/development of the physics engine, real-time rendering and post-processing features",
              "Led design/development of a node-based visual code system",
              "Ran an external beta test",
            ],
          },
          {
            role: "Project Leader",
            productLabel: "Product",
            product: "Dr.Meta",
            period: "2024.06 - 2025.01",
            title: "Metaverse platform used by cancer centers nationwide",
            subtitle: "Development of 'Dr.Meta' (Korea Smart Healthcare Association)",
            brief: [
              "Led design/development of the React web app ↔ Unity app integration and admin/permission features",
              "In commercial operation at cancer centers nationwide ([web.drmeta.kr](http://web.drmeta.kr/))",
            ],
            details: [
              "Led a task force team of planners, designers, developers and QA",
              "Led design/development of the integration between a React-based web app and a Unity app",
              "Led design/development of the admin page and permission features",
              "In commercial operation at cancer centers nationwide ([web.drmeta.kr](http://web.drmeta.kr/))",
            ],
          },
          {
            role: "Project Leader",
            product: "Meta.CRO",
            period: "2023.06 - 2025.01",
            title: "3D-based virtual simulation training platform for clinical trials",
            subtitle: "Development of 'Meta.CRO' (Korea Smart Healthcare Association)",
            brief: [
              "Designed and released a 3D render engine library (private npm); led a development/QA task force",
              "In commercial operation at cancer centers nationwide",
            ],
            details: [
              "Led a task force team of developers and QA",
              "Designed and released a 3D render engine library (set up a private npm environment)",
              "In commercial operation at cancer centers nationwide",
            ],
          },
          {
            role: "Project Leader",
            product: "NaenunN",
            period: "2024.03 - 2024.09",
            title: "Online marketplace platform for contact lenses",
            subtitle: "Development of 'NaenunN' (Pixelro)",
            brief: [
              "The first online contact-lens purchase & delivery service, opened under a regulatory sandbox exemption — led the React Native cross-platform app; in commercial operation",
            ],
            details: [
              "Led a task force team of developers and QA",
              "Developed, together with the partner company, an online contact lens purchase and delivery service first permitted under a regulatory sandbox special exemption for demonstration",
              "Led design/development of a cross-platform app from a single core codebase using React and React Native",
              "Led builds and releases to meet Android and iOS review requirements",
              "In commercial operation ([nenoonn.mycafe24.com](https://nenoonn.mycafe24.com/))",
            ],
          },
          {
            role: "Project Leader",
            product: "GIS S-DCIS",
            period: "2023.12 - 2024.08",
            title: "GIS-based Samsung data center information system",
            subtitle: "Development of 'GIS S-DCIS' (Samsung C&T)",
            brief: [
              "GIS system on GeoServer · PostGIS · OpenLayers, built for a closed-network on-premise environment — co-developed and delivered with Yeonwoo Technology (B2B)",
            ],
            details: [
              "Communicated and collaborated with the planning team, the business team and another company's research team",
              "Built a spatial function server and DB using GeoServer and PostGIS",
              "Researched Openlayers open-source technology to build a map platform on GIS data",
              "Used public data and handled policy issues",
              "Troubleshot issues in migrating source code to a closed network and setting up an on-premise environment",
              "Co-developed with Yeonwoo Technology development researchers and delivered (B2B)",
            ],
          },
          {
            role: "Project Leader",
            product: "MVS",
            period: "2023.01 - 2024.09",
            title: "Real-time multi-sync server",
            subtitle: "Research on ’MVS: Metaverse Server’ (internal project)",
            brief: [
              "Researched and developed a C++ real-time multi-user sync server engine — applied as the multiplayer server for Dr.Meta's medical staff conferences",
            ],
            details: [
              "Led the R&D team; researched and developed C++-based server engine technology",
              "Designed client libraries (Javascript, C#)",
              "Designed the service flow",
              "Applied the researched technology as the multiplayer server for Dr.Meta's medical staff conferences",
            ],
          },
        ],
      },
      {
        role: "Project Leader",
        company: "TmaxAI",
        department: "Meta Vision Research Division / Researcher (Head of Office, concurrently Division Head)",
        tenure: "2020.07 - 2022.06",
        highlights: [
          "R&D Division Head (concurrently Head of Office) — led an R&D organization of up to 50",
          "Acted as technical lead for about a year while the CTO role was vacant",
        ],
        projects: [
          {
            role: "Project Leader",
            productLabel: "Project",
            product: "Mint",
            period: "2021.07 - 2022.06",
            title: "Metaverse education platform",
            subtitle: "Development of 'Mint'",
            brief: [
              "Planned and built a metaverse education platform on Phaser · WebRTC · WebGL — delivered to Kongju National University",
            ],
            details: [
              "Planned the product using Gather Town as a benchmark",
              "Used open-source technologies including the Phaser game engine, WebRTC, WebGL, React and MobX",
              "Delivered to Kongju National University as a metaverse education platform",
            ],
          },
          {
            role: "Project Leader",
            productLabel: "Research",
            product: "Digital human and metaverse space research",
            period: "2020.07 - 2021.06",
            title: "Advanced technology research",
            subtitle: "Deep Learning, 3DMM, SLAM",
            brief: [
              "Early research on deep-learning digital humans (TTS) and SLAM-based 3D space generation — demoed at Tmax Day 2020",
            ],
            details: [
              "As advanced technology research, studied generating digital humans capable of Deep Learning-based text-to-speech",
              "As advanced technology research, studied generating metaverse spaces using Deep Learning-based SLAM 3D spatial technology",
              "Used Blender and WebGL open source",
              "Demonstrated at the demo booth of the 2020 Tmax Day conference",
            ],
          },
        ],
      },
      {
        role: "Product Engineer",
        company: "TmaxA&C",
        department: "Graphics Research Division / Researcher (Team Lead)",
        tenure: "2017.01 - 2020.07",
        projects: [
          {
            role: "Product Engineer",
            product: "WAPL",
            period: "2019.01 - 2020.06",
            title: "Collaboration solution",
            subtitle: "Development of 'WAPL'",
            brief: ["Frontend development of the collaboration solution's calendar and messenger — commercialized by TmaxWAPL"],
            details: [
              "Developed calendar and messenger features (frontend)",
              "In commercial operation by TmaxWAPL",
            ],
          },
          {
            role: "Product Engineer",
            product: "TmaxOS",
            period: "2017.06 - 2018.12",
            title: "Linux-based product",
            subtitle: "Development of 'TmaxOS'",
            brief: ["C++ development for a Linux-based OS — built and refactored the settings screen and video player"],
            details: [
              "Developed in C++",
              "Fixed bugs in the OS personal settings section (frontend)",
              "Developed a video player and refactored its code",
            ],
          },
          {
            role: "Structure analysis & refactoring design",
            product: "Anylink",
            period: "2017.02 - 2017.06",
            title: "Integrated system interface solution software",
            subtitle: "Structure analysis of 'Anylink'",
            brief: ["Structure analysis and refactoring design of an integrated interface solution — identified improvements with the engine research team; a TmaxSoft commercial product"],
            details: [
              "Took part in structure analysis and refactoring design of the integrated system interface solution",
              "Worked with the engine research team to identify usability and quality improvement points",
              "In commercial operation by TmaxSoft ([Product overview](https://www.tmaxsoft.com/kr/solution/view?solutionSeq=9))",
            ],
          },
        ],
      },
    ],
  },
];
