// Source: Notion "직무 및 이력 (Experiences)" — each company toggle and its nested project callouts.

import type { Experience } from "@/types/content";

export const experiences: Experience[] = [
  {
    role: "Head of Product Dev Team",
    company: "Studio XID (ProtoPie)",
    department: "Product Dev Team",
    tenure: "2026.01 - Present",
    mission: "Take design-to-code AI from PoC to official launch — completed with the ProtoPie MCP launch (2026.10)",
    projects: [
      {
        role: "Design & development (solo)",
        productLabel: "New product PoC",
        product: "[Decision Graph](/projects/decision-graph)",
        period: "2026.08 - 2026.10",
        title: "LLM pipeline for decision extraction",
        subtitle: "(Slack·Notion → decision records with evidence)",
        details: [
          "Turned PO requirements into a tech spec and built (solo) an LLM PoC that extracts who decided what and why, with evidence",
          "Auto-visualized decisions as a relation map and timeline, each linked to its source text",
          "Validated on a human-labeled golden set from one real project — extracted 80%+ of the labeled decisions",
          "Tested key risks in the PoC: human ground truth, one-way records, no duplicates on re-runs",
          "Two-tier inference (light model triages, strong model extracts/verifies), chosen by tests; all-light 17/24",
          "Profiled per-request time and cost: 74% fewer calls (1,289 → 336), 25% lower cost ($10.2 → $7.6); incremental $0.7",
          "Checked every change against 24 test cases, with a cap on evaluation cost",
        ],
      },
      {
        role: "Head of Product Dev Team",
        product: "[ProtoPie MCP](https://www.protopie.io/blog/protopie-mcp-official) (Dev View · Code MCP) official launch",
        period: "2026.01 - 2026.10",
        title: "AI-based code generation system",
        subtitle: "(PoC → productization)",
        details: [
          "[Hands-on] Designed the rules + AI-stage code generation pipeline and built its core (PoC)",
          "[Hands-on] Designed training for image/layout-understanding models and built the training data",
          "[Hands-on] Designed how the pipeline integrates into the existing product (ProtoPie)",
          "[Team lead] Ran a 4–5 person agile team — AI engineers trained the models; integration built with the team",
          "[Team lead] Designed the MLOps pipeline from data cleaning → training → deployment",
          "[Team lead] Expanded to AOS, iOS and Web; launched as ProtoPie MCP in Oct 2026 (7 frameworks)",
        ],
      },
    ],
  },
  {
    role: "Product Owner",
    company: "ESTsoft",
    department: "AI Agent Lab / Alan Development Team / PO",
    tenure: "2025.04 - 2026.01",
    mission: "Turn the pilot service Alan into a paid product — done with the Pro launch (2025.07) and first paid revenue",
    projects: [
      {
        role: "Product Owner",
        product: "Alan",
        period: "2025.04 - 2026.01",
        title: "AI search engine service (LLM-based agentic AI)",
        subtitle: "Advancing ’Alan’ (ESTsoft)",
        details: [
          "As PO, led the AI researcher and FE/BE developer team taking a research pilot service to commercial launch and monetization",
          "Architected on Azure, FastAPI, React and LangGraph with separate Dev/QA/Stage/Release environments",
          "Owned feature planning, schedule and risk; ran quality testing with QA, auth, payments and infra teams",
          "Built in-house agents for image search, YouTube summaries and report generation",
          "Led slide generation planning — Genspark benchmark, user scenarios and generation flow",
          "Designed the slide agent: staged orchestration (intent → scope → research → style → HTML → revision), human-in-the-loop",
          "Planned AI monetization: priced Pro and usage limits from inference cost per call, competitors and expected conversion",
          "Led the paid launch as PO — entitlements, payment/cancel/refund flows, terms and notices, launch with marketing and business (2025.07, [announcement](https://estsoft.ai/all/250707))",
          "Shipped deep research, slide generation and a back-office tool; in commercial operation ([myalan.ai](https://myalan.ai/))",
          "First paid revenue from Pro (not disclosed); then planned an enterprise product, later the basis for institutional contracts",
        ],
      },
    ],
  },
  {
    // Grouped as one because the department moved between Tmax affiliates (newest affiliate first)
    company: "Tmax Group",
    tenure: "2017.01 - 2025.04",
    units: [
      {
        role: "Project Leader, Development Team",
        company: "TmaxMetaAI",
        department: "Meta AI Research Division / Researcher (Head of Office)",
        tenure: "2022.07 - 2025.04",
        projects: [
          {
            role: "Project Leader",
            product: "MX studio",
            period: "2022.07 - 2025.02",
            title: "Software for building 3D web components",
            subtitle: "'MX studio' and productization on it",
            brief: [
              "Led the MX studio engine team and a task force (planning, design, development, QA)",
              "Led the physics engine, real-time rendering, 3D events/actions and a node-based visual code system",
              "Productized Dr.Meta and Meta.CRO on its output; ran an external beta test",
            ],
            details: [
              "Led the MX studio engine team",
              "Led a task force team of planners, designers, developers and QA",
              "Led design/development of events and actions for 3D objects",
              "Led design/development of the physics engine, real-time rendering and post-processing features",
              "Led design/development of a node-based visual code system",
              "Ran an external beta test",
            ],
          },
          {
            role: "Project Leader",
            productLabel: "Product",
            product: "Dr.Meta",
            period: "2024.06 - 2025.01",
            title: "Metaverse platform used by cancer centers nationwide",
            subtitle: "Development of 'Dr.Meta' (Korea Smart Healthcare Association)",
            brief: [
              "Led design/development of the React web app ↔ Unity app integration and admin/permission features",
              "In commercial operation at cancer centers nationwide ([web.drmeta.kr](http://web.drmeta.kr/))",
            ],
            details: [
              "Led a task force team of planners, designers, developers and QA",
              "Led design/development of the integration between a React-based web app and a Unity app",
              "Led design/development of the admin page and permission features",
              "In commercial operation at cancer centers nationwide ([web.drmeta.kr](http://web.drmeta.kr/))",
            ],
          },
          {
            role: "Project Leader",
            product: "Meta.CRO",
            period: "2023.06 - 2025.01",
            title: "3D-based virtual simulation training platform for clinical trials",
            subtitle: "Development of 'Meta.CRO' (Korea Smart Healthcare Association)",
            brief: [
              "Designed and released a 3D render engine library (private npm); led a development/QA task force",
              "In commercial operation at cancer centers nationwide",
            ],
            details: [
              "Led a task force team of developers and QA",
              "Designed and released a 3D render engine library (set up a private npm environment)",
              "In commercial operation at cancer centers nationwide",
            ],
          },
          {
            role: "Project Leader",
            product: "NaenunN",
            period: "2024.03 - 2024.09",
            title: "Online marketplace platform for contact lenses",
            subtitle: "Development of 'NaenunN' (Pixelro)",
            brief: [
              "First online contact-lens sales service (regulatory sandbox) — shipped WebView iOS/Android apps, led payment/delivery API and admin design; in operation",
            ],
            details: [
              "Led a task force team of developers and QA",
              "Developed, together with the partner company, an online contact lens purchase and delivery service first permitted under a regulatory sandbox special exemption for demonstration",
              "Designed the frontend–backend data flow and server sequences, and reviewed technical risks",
              "Shipped separate iOS and Android apps as a WebView-based cross-platform app over a React web app; led builds and releases for store review",
              "Designed external API integrations (payment, delivery) and the operations admin (central and per-store)",
              "In commercial operation ([nenoonn.mycafe24.com](https://nenoonn.mycafe24.com/))",
            ],
          },
          {
            role: "Project Leader",
            product: "GIS S-DCIS",
            period: "2023.12 - 2024.08",
            title: "GIS-based Samsung data center information system",
            subtitle: "Development of 'GIS S-DCIS' (Samsung C&T)",
            brief: [
              "GIS system on GeoServer · PostGIS · OpenLayers for a closed on-premise network — co-developed with Yeonwoo Technology (B2B)",
            ],
            details: [
              "Communicated and collaborated with the planning team, the business team and another company's research team",
              "Built a spatial function server and DB using GeoServer and PostGIS",
              "Researched Openlayers open-source technology to build a map platform on GIS data",
              "Used public data and handled policy issues",
              "Troubleshot issues in migrating source code to a closed network and setting up an on-premise environment",
              "Co-developed with Yeonwoo Technology development researchers and delivered (B2B)",
            ],
          },
          {
            role: "Project Leader",
            product: "MVS",
            period: "2023.01 - 2024.09",
            title: "Real-time multi-sync server",
            subtitle: "Research on ’MVS: Metaverse Server’ (internal project)",
            brief: [
              "Built a C++ real-time multi-user sync server engine — used as the multiplayer server for Dr.Meta conferences",
            ],
            details: [
              "Led the R&D team; researched and developed C++-based server engine technology",
              "Designed client libraries (Javascript, C#)",
              "Designed the service flow",
              "Applied the researched technology as the multiplayer server for Dr.Meta's medical staff conferences",
            ],
          },
        ],
      },
      {
        role: "Project Leader",
        company: "TmaxAI",
        department: "Meta Vision Research Division / Researcher (Head of Office, concurrently Division Head)",
        tenure: "2020.07 - 2022.06",
        highlights: [
          "R&D Division Head (concurrently Head of Office) — led an R&D organization of up to 50",
          "Acted as technical lead for about a year while the CTO role was vacant",
          "Ran evaluations and feedback for team members and team leads",
        ],
        projects: [
          {
            role: "Project Leader",
            productLabel: "Project",
            product: "Mint",
            period: "2021.07 - 2022.06",
            title: "Metaverse education platform",
            subtitle: "Development of 'Mint'",
            brief: [
              "Built a metaverse education platform (Phaser, WebRTC, WebGL) — delivered to Kongju National Univ.",
            ],
            details: [
              "Planned the product using Gather Town as a benchmark",
              "Used open-source technologies including the Phaser game engine, WebRTC, WebGL, React and MobX",
              "Delivered to Kongju National University as a metaverse education platform",
            ],
          },
          {
            role: "Project Leader",
            productLabel: "Research",
            product: "Digital human and metaverse space research",
            period: "2020.07 - 2021.06",
            title: "Advanced technology research",
            subtitle: "Deep Learning, 3DMM, SLAM",
            brief: [
              "Research on deep-learning digital humans (TTS) and SLAM 3D spaces — demoed at Tmax Day 2020",
            ],
            details: [
              "As advanced technology research, studied generating digital humans capable of Deep Learning-based text-to-speech",
              "As advanced technology research, studied generating metaverse spaces using Deep Learning-based SLAM 3D spatial technology",
              "Used Blender and WebGL open source",
              "Demonstrated at the demo booth of the 2020 Tmax Day conference",
            ],
          },
        ],
      },
      {
        role: "Product Engineer",
        company: "TmaxA&C",
        department: "Graphics Research Division / Researcher (Team Lead)",
        tenure: "2017.01 - 2020.07",
        projects: [
          {
            role: "Product Engineer",
            product: "WAPL",
            period: "2019.01 - 2020.06",
            title: "Collaboration solution",
            subtitle: "Development of 'WAPL'",
            brief: ["Frontend development of the collaboration solution's calendar and messenger — commercialized by TmaxWAPL"],
            details: [
              "Developed calendar and messenger features (frontend)",
              "In commercial operation by TmaxWAPL",
            ],
          },
          {
            role: "Product Engineer",
            product: "TmaxOS",
            period: "2017.06 - 2018.12",
            title: "Linux-based product",
            subtitle: "Development of 'TmaxOS'",
            brief: ["C++ development for a Linux-based OS — built and refactored the settings screen and video player"],
            details: [
              "Developed in C++",
              "Fixed bugs in the OS personal settings section (frontend)",
              "Developed a video player and refactored its code",
            ],
          },
          {
            role: "Structure analysis & refactoring design",
            product: "Anylink",
            period: "2017.02 - 2017.06",
            title: "Integrated system interface solution software",
            subtitle: "Structure analysis of 'Anylink'",
            brief: ["Structure analysis and refactoring design of an integration solution — a TmaxSoft commercial product"],
            details: [
              "Took part in structure analysis and refactoring design of the integrated system interface solution",
              "Worked with the engine research team to identify usability and quality improvement points",
              "In commercial operation by TmaxSoft ([Product overview](https://www.tmaxsoft.com/kr/solution/view?solutionSeq=9))",
            ],
          },
        ],
      },
    ],
  },
];
