// Source: Notion "직무 및 이력 (Experiences)" — each company toggle and its nested project callouts.

import type { Experience } from "@/types/content";

export const experiences: Experience[] = [
  {
    role: "Head of Dev Team",
    company: "스튜디오씨드코리아(프로토파이)",
    department: "Product Dev Team/ Head",
    tenure: "2026.01.06 - 현재",
    projects: [
      {
        role: "설계·개발 (1인)",
        productLabel: "사내 도구",
        product: "[Decision Graph](/projects/decision-graph)",
        period: "2026.08 - 2026.10",
        title: "의사결정 추출 LLM 파이프라인",
        subtitle: "(Slack·Notion → 근거 있는 결정 기록)",
        details: [
          "Slack·Notion에서 '누가·무엇을·왜' 결정했는지 원문 근거와 함께 추출하는 LLM 파이프라인 1인 설계·개발",
          "최근 1년 내 실제 진행한 프로젝트 1건을 골든셋으로 정해 PoC 결과 검증 — 신뢰도 80% 이상 확인",
          "PoC로 우려되던 기술 리스크를 직접 검증·검토 (신뢰도 % 대신 정답 케이스로 판단, 단방향 기록, 재실행 중복 반영 방지)",
          "2-tier 추론 구조(1차 분류: 경량 모델, 추출·검증: 고성능 모델)를 같은 테스트 케이스로 비교해 결정",
          "요청별 시간·비용을 기록해 병목을 찾고 호출 구조 개선 — 같은 데이터 기준 1,289회·$10.2 → 336회·$7.6, 바뀐 부분만 다시 돌리면 30회·$0.7",
          "정답을 정해 둔 테스트 케이스 23개로 수정할 때마다 품질 확인 (평가 비용 상한 설정)",
        ],
      },
      {
        role: "Head of Product Dev Team",
        product: "[ProtoPie MCP](https://www.protopie.io/blog/protopie-mcp-official) (Dev View · Code MCP) 정식 출시",
        title: "AI 기반 코드 생성 시스템",
        subtitle: "(PoC → 제품화)",
        details: [
          "AI 기반 코드 생성 시스템 전체 설계 및 개발 팀 리드",
          "AI 엔지니어 및 앱 개발자로 구성된 4~5명 애자일 팀 운영",
          "룰 기반 모듈과 AI 모델 단계를 결합한 코드 생성 파이프라인 설계 (직접 주도)",
          "이미지 기반·레이아웃(구조) 기반 코드 변환을 보조하는 모델의 학습 설계, 라벨링 등 학습 데이터 구축 (학습은 AI 엔지니어 담당)",
          "데이터 정제부터 학습·배포까지 이어지는 MLOps 파이프라인 설계",
          "AOS·iOS·Web 크로스 플랫폼 컴포넌트 코드 생성 파이프라인 구축",
          "코어 파이프라인 직접 개발(PoC) → 팀과 함께 제품화 → 2026년 10월 ProtoPie MCP로 정식 출시 (Dev View · Code MCP, 7개 프레임워크 코드 생성 지원)",
        ],
      },
    ],
  },
  {
    role: "Product Owner",
    company: "이스트소프트",
    department: "AI Agent Lab / Alan 개발 파트 / PO",
    tenure: "2025.04.22 - 2026.01.05",
    projects: [
      {
        role: "Product Owner",
        product: "Alan",
        period: "2025.04 - 2026.01",
        title: "AI 검색 엔진 서비스 (LLM 기반 Agentic AI)",
        subtitle: "’Alan’ 고도화 (이스트소프트)",
        details: [
          "연구 조직에서 시험 운영 중이던 서비스를 상용화·수익화까지 리드",
          "LLM 기반의 Agentic AI 앱 서비스 개발 파트 리드하며 Product Owner 업무 수행",
          "AI 연구원 및 앱 개발자(FE, BE)로 구성된 파트 리드",
          "Dev, QA, Stage, Release 서버 분리하여 운영, 관리",
          "Azure, Fast API, React, LangGraph 구조 아키텍처링",
          "품질 테스트 및 사내 타 부서 (QA, 인증, 결제, 인프라 등) 개발/품질/인프라 팀과 협업",
          "LLM 기반 AI 앱 서비스 기능 기획, 일정, 리스크 관리",
          "이미지 서치, 유튜브 서치·요약, 보고서 생성, 슬라이드 생성 기능과 특화 에이전트 독자 개발 (슬라이드 생성은 조사·기획부터 주도)",
          "결제 시스템 프로세스 및 상품 유료화 정책 수립",
          "딥리서치·슬라이드 생성 서비스 배포, Pro 구독 서비스 런칭, 백오피스 내부 운영 툴 개발",
          "상용화 운영 중 [(https://myalan.ai/)](https://myalan.ai/)",
        ],
      },
    ],
  },
  {
    role: "개발팀 Project Leader",
    company: "티맥스메타에이아이",
    department: "Meta AI 연구본부 / 연구원 (실장)",
    tenure: "2022.07.01 - 2025.04.14",
    projects: [
      {
        role: "Project Leader",
        product: "MX studio",
        period: "2022.07 -",
        title: "3D Web Component 제작 소프트웨어",
        subtitle: "'MX studio' 개발 및 이를 기반으로 한 제품화",
        details: [
          "MX studio 엔진팀 리드하며 Project Leader 업무 수행",
          "기획, 디자이너, 개발자, QA로 구성된 TF팀 리드",
          "3D 물체의 이벤트와 액션 기능 설계/개발 리드",
          "물리 엔진과 실시간 렌더링 및 후처리 기능 설계/개발 리드",
          "Node 기반의 visual code system 설계/개발 리드",
          "외부 Beta test 진행 중 ([https://www.mxstudio.store/](https://www.mxstudio.store/))",
        ],
      },
      {
        role: "Project Leader",
        productLabel: "제품",
        product: "닥터메타",
        period: "2024.06 - 2025.01",
        title: "전국 암센터 활용 메타버스 플랫폼",
        subtitle: "'닥터메타' 개발 (한국스마트헬스케어협회)",
        details: [
          "앱 개발 TF팀 리드하며 Project Leader 업무 수행",
          "기획, 디자이너, 개발자, QA로 구성된 TF팀 리드",
          "React 기반의 웹 앱과 Unity 앱 연동 설계/개발 리드",
          "관리자 페이지 및 권한 기능 설계/개발 리드",
          "전국 암센터에서 상용 운영 ([web.drmeta.kr](http://web.drmeta.kr/))",
        ],
      },
      {
        role: "Project Leader",
        product: "Meta.CRO",
        period: "2023.01 - 2024.01",
        title: "3D 기반 임상시험 가상 시뮬레이션 교육 플랫폼",
        subtitle: "'Meta.CRO' 개발 (한국스마트헬스케어협회)",
        details: [
          "앱 개발 TF팀 리드하며 Project Leader 업무 수행",
          "개발자, QA로 구성된 TF팀 리드",
          "3D render engine library 설계/배포 (private npm 환경 구성)",
          "전국 암센터에서 상용 운영 ([https://www.crotraining.store/](https://www.crotraining.store/))",
        ],
      },
      {
        role: "Project Leader",
        product: "내눈N",
        period: "2024.03 - 2024.09",
        title: "콘택트렌즈 온라인 마켓 플랫폼",
        subtitle: "'내눈N' 개발 (픽셀로)",
        details: [
          "앱 개발 TF팀 리드하며 Project Leader 업무 수행",
          "개발자, QA로 구성된 TF팀 리드",
          "규제 샌드박스 실증특례로 처음 허용된 콘택트렌즈 온라인 구매·배송 서비스를 업체와 함께 개발",
          "React, React Native를 활용하여 core 소스 하나로 크로스플랫폼 앱 설계/개발 리드",
          "Android, iOS 심사에 맞게 빌드 및 배포 리드",
          "상용화 운영 중 ([https://nenoonn.mycafe24.com/](https://nenoonn.mycafe24.com/))",
        ],
      },
      {
        role: "Project Leader",
        product: "GIS S-DCIS",
        period: "2023.12 - 2024.08",
        title: "GIS 기반 삼성 데이터 센터 정보 시스템",
        subtitle: "'GIS S-DCIS' 개발 (삼성물산)",
        details: [
          "앱 개발 TF팀 리드하며 Project Leader 업무 수행",
          "기획팀, 사업팀, 타사 연구팀과 소통 및 협업",
          "GeoServer와 PostGIS를 활용한 공간함수 서버 및 DB 구축",
          "GIS 데이터 기반의 map platform 구성을 위한 Openlayers 오픈소스 기술 연구",
          "공공 데이터 활용 및 정책 이슈 핸들링",
          "폐쇄망 소스 이관 및 On-Premise 환경 구축 시 생기는 이슈 트러블슈팅",
          "연우테크놀러지 개발 연구원들과 공동 개발 후 납품 (B2B)",
        ],
      },
      {
        role: "Project Leader",
        product: "MVS",
        period: "2023.12 - 2024.08",
        title: "실시간 다중 동기화 서버",
        subtitle: "’MVS: Metaverse Server’ 연구 (사내 프로젝트)",
        details: [
          "R&D 팀 리드하며 C++ 기반의 서버 엔진 기술 연구 및 개발",
          "Client Library 설계 (Javascript, C#)",
          "서비스 플로우 설계",
          "연구 기술을 닥터메타 의료진 컨퍼런스의 멀티플레이 서버로 적용",
        ],
      },
    ],
  },
  {
    role: "Project Leader",
    company: "티맥스에이아이",
    department: "Meta Vision 연구본부 / 연구원 (실장, 본부장 겸직)",
    tenure: "2020.07.25 - 2022.06.30",
    projects: [
      {
        role: "Project Leader",
        productLabel: "프로젝트명",
        product: "Mint",
        period: "2021.07 - 2022.06",
        title: "메타버스 교육 플랫폼",
        subtitle: "'Mint' 개발",
        details: [
          "Project Leader로서 설계/개발/관리 업무 수행",
          "게더타운을 벤치마크 하여 제품 기획",
          "Game engine Phaser, WebRTC, WebGL, React, MobX 등 오픈소스 기술 활용",
          "공주대학교에 메타버스 교육 플랫폼으로 납품 완료 (참고: [https://m.post.naver.com/viewer/postView.naver?volumeNo=37517956&memberNo=57597506](https://m.post.naver.com/viewer/postView.naver?volumeNo=37517956&memberNo=57597506))",
        ],
      },
      {
        role: "Project Leader",
        productLabel: "기술 연구",
        product: "디지털 휴먼, 메타버스 공간 연구",
        period: "2020.07 - 2021.06",
        title: "선행 기술 연구",
        subtitle: "Deep Learning, 3DMM, SLAM 진행",
        details: [
          "Project Leader로서 설계/개발/관리 업무 수행",
          "선행 기술 연구로, Deep Learning 기반의 Text-to-Speech가 가능한 디지털 휴먼 생성 연구 수행",
          "선행 기술 연구로, Deep Learning 기반의 SLAM 3D 공간 기술을 활용한 메타버스 공간 생성 연구 수행",
          "Blender 및 WebGL 오픈소스 활용",
          "2020 티맥스데이 컨퍼런스 데모 부스에서 시연",
        ],
      },
    ],
  },
  {
    role: "Product Engineer",
    company: "티맥스에이앤씨",
    department: "Graphics 연구본부 / 연구원 (팀장)",
    tenure: "2017.02.01 - 2020.07.24",
    projects: [
      {
        role: "Product Engineer",
        product: "WAPL",
        period: "2019.01 - 2020.06",
        title: "협업 솔루션",
        subtitle: "'WAPL' 개발",
        details: [
          "캘린더 및 메신저 기능 개발(frontend) 업무 수행",
          "티맥스와플 사에서 상용화 운영 중 ([https://wapl.ai/](https://wapl.ai/))",
        ],
      },
      {
        role: "Product Engineer",
        product: "TmaxOS",
        period: "2017.06 - 2018.12",
        title: "Linux 기반 제품",
        subtitle: "'TmaxOS' 개발",
        details: ["C++을 활용한 개발", "OS 개인 설정 섹션(frontend) 버그 수정 및 해결", "Video player 개발 및 코드 리팩토링"],
      },
      {
        role: "구조 분석 및 리팩토링 설계",
        product: "Anylink",
        period: "2017.02 - 2017.06",
        title: "통합 시스템 인터페이스 솔루션 소프트웨어",
        subtitle: "'Anylink' 구조 분석",
        details: [
          "통합 시스템 인터페이스 솔루션의 구조 분석 및 리팩토링 설계 참여",
          "엔진 연구팀과 협업하여 사용성·품질 개선 포인트 도출",
          "티맥스소프트 사에서 상용화 운영 중 ([https://www.tmaxsoft.com/kr/solution/view?solutionSeq=9](https://www.tmaxsoft.com/kr/solution/view?solutionSeq=9))",
        ],
      },
    ],
  },
];
