// Generated by scripts/prepare-assets.mjs — do not edit by hand.
export const profileImage = {"src":"/images/profile.webp","width":354,"height":472} as const;

export const projectImages: Record<string, { src: string; width: number; height: number }[]> = {
  "alan": [
    {
      "src": "/projects/alan/02.webp",
      "width": 487,
      "height": 691
    },
    {
      "src": "/projects/alan/05.webp",
      "width": 547,
      "height": 1261
    }
  ],
  "mx-studio": [
    {
      "src": "/projects/mx-studio/01.webp",
      "width": 1915,
      "height": 1069
    },
    {
      "src": "/projects/mx-studio/02.webp",
      "width": 1917,
      "height": 1004
    },
    {
      "src": "/projects/mx-studio/03.webp",
      "width": 1907,
      "height": 1022
    },
    {
      "src": "/projects/mx-studio/04.webp",
      "width": 1837,
      "height": 983
    },
    {
      "src": "/projects/mx-studio/05.webp",
      "width": 1906,
      "height": 1065
    }
  ],
  "dr-meta": [
    {
      "src": "/projects/dr-meta/01.webp",
      "width": 1907,
      "height": 1059
    },
    {
      "src": "/projects/dr-meta/02.webp",
      "width": 1914,
      "height": 1067
    },
    {
      "src": "/projects/dr-meta/03.webp",
      "width": 1911,
      "height": 1060
    },
    {
      "src": "/projects/dr-meta/04.webp",
      "width": 1920,
      "height": 1282
    },
    {
      "src": "/projects/dr-meta/05.webp",
      "width": 1920,
      "height": 1294
    },
    {
      "src": "/projects/dr-meta/06.webp",
      "width": 1910,
      "height": 1063
    },
    {
      "src": "/projects/dr-meta/07.webp",
      "width": 1909,
      "height": 1060
    },
    {
      "src": "/projects/dr-meta/08.webp",
      "width": 1908,
      "height": 1070
    },
    {
      "src": "/projects/dr-meta/09.webp",
      "width": 1829,
      "height": 1128
    },
    {
      "src": "/projects/dr-meta/10.webp",
      "width": 1920,
      "height": 1293
    }
  ],
  "meta-cro": [
    {
      "src": "/projects/meta-cro/01.webp",
      "width": 512,
      "height": 308
    },
    {
      "src": "/projects/meta-cro/02.webp",
      "width": 512,
      "height": 288
    },
    {
      "src": "/projects/meta-cro/03.webp",
      "width": 1247,
      "height": 832
    }
  ],
  "nenoonn": [
    {
      "src": "/projects/nenoonn/01.webp",
      "width": 641,
      "height": 1401
    },
    {
      "src": "/projects/nenoonn/02.webp",
      "width": 647,
      "height": 1384
    },
    {
      "src": "/projects/nenoonn/03.webp",
      "width": 642,
      "height": 1385
    },
    {
      "src": "/projects/nenoonn/04.webp",
      "width": 643,
      "height": 1377
    },
    {
      "src": "/projects/nenoonn/05.webp",
      "width": 642,
      "height": 1384
    }
  ],
  "gis-s-dcis": [
    {
      "src": "/projects/gis-s-dcis/01.webp",
      "width": 1591,
      "height": 777
    },
    {
      "src": "/projects/gis-s-dcis/02.webp",
      "width": 1920,
      "height": 993
    },
    {
      "src": "/projects/gis-s-dcis/03.webp",
      "width": 1920,
      "height": 994
    },
    {
      "src": "/projects/gis-s-dcis/04.webp",
      "width": 1920,
      "height": 990
    },
    {
      "src": "/projects/gis-s-dcis/05.webp",
      "width": 1920,
      "height": 995
    }
  ],
  "mvs": [
    {
      "src": "/projects/mvs/01.webp",
      "width": 1700,
      "height": 1044
    },
    {
      "src": "/projects/mvs/02.webp",
      "width": 1913,
      "height": 1066
    },
    {
      "src": "/projects/mvs/03.webp",
      "width": 1362,
      "height": 976
    }
  ]
};
