// Fixed UI copy (buttons, field names, alt text). Components read from here instead of inlining strings.

export const labels = {
  meta: {
    titleTemplate: "%s | 이석우 포트폴리오",
    resumeDescription: (name: string, position: string) => `${name} — ${position} 이력서: 경력, 프로젝트, 스킬, 학위, 수상`,
  },
  nav: {
    home: "Home",
    openMenu: "메뉴 열기",
    closeMenu: "메뉴 닫기",
    main: "주 메뉴",
    toDark: "다크 모드로 전환",
    toLight: "라이트 모드로 전환",
    languageSwitch: "English",
    languageSwitchLabel: "영어로 보기",
  },
  profile: {
    contact: "연락처",
    documents: "PDF",
    downloadResume: "이력서 PDF 다운로드",
    resumePdfNote: "이 페이지 내용으로 만든 최신 이력서",
    resumePdfFileName: "이석우_이력서.pdf",
    printFooter: (url: string) => `이 이력서는 ${url} 의 내용으로 생성되었습니다.`,
    lastUpdated: "Last updated",
    photoAlt: (name: string) => `${name} 프로필 사진`,
  },
  resume: {
    toc: "목차",
  },
  experience: {
    department: "부서 직책",
    tenure: "재직 날짜",
    defaultProductLabel: "제품명",
    details: "세부 내용",
    tenureLength: (years: number, months: number) => [years && `${years}년`, months && `${months}개월`].filter(Boolean).join(" ") || "1개월 미만",
  },
  projects: {
    featured: "대표 프로젝트",
    more: "그 밖의 프로젝트",
    viewAll: "전체 프로젝트 보기 →",
    readCase: "자세히 보기 →",
    backToList: "← 프로젝트 목록",
    prev: "← 이전 프로젝트",
    next: "다음 프로젝트 →",
    pagerLabel: "다른 프로젝트",
    total: (count: number) => `총 ${count}개 프로젝트`,
    imageCount: (count: number) => `${count} images`,
    coverAlt: (name: string) => `${name} 대표 이미지`,
    screenshotAlt: (name: string, index: number, total: number) => `${name} 스크린샷 ${index}/${total}`,
    caseStudy: {
      title: "요약",
      problem: "문제",
      decisions: "핵심 결정",
    },
    detailsTitle: "상세",
    fields: {
      fullName: "프로젝트 명",
      domain: "고객사 · 분야",
      period: "수행 기간",
      tasks: "업무 내용",
      roles: "담당 역할",
      skills: "사용 기술",
    },
  },
  home: {
    metricsLabel: "주요 지표",
    latestWorkCta: "적용 사례 보기 ↗",
  },
  contact: {
    eyebrow: "Contact",
    title: "이야기 나눠요",
    description: "AI를 실제 서비스로 옮기는 고민, 개발 조직을 꾸리는 고민이라면 편하게 연락 주세요.",
    mailSubject: "[포트폴리오] 문의",
    copyHint: "클릭하면 복사",
    copyEmailLabel: (email: string) => `이메일 주소 ${email} 복사`,
    copied: "복사됨 ✓",
    copyFailed: "복사 실패",
  },
  activityKinds: { award: "수상", paper: "논문·학술", activity: "활동" },
  studentActivities: (count: number) => `학생 시절 수상·활동 (2010–2013) · ${count}`,
  footer: {
    backToTop: "맨 위로 ↑",
  },
  notFound: {
    code: "404",
    title: "페이지를 찾을 수 없어요",
    home: "홈으로 돌아가기 →",
  },
};
