// Source: Notion "프로젝트 (Project)" database — row properties + each project page body.
import type { ImageAsset, Project } from "@/types/content";
import { projectImages } from "./images.generated";

const list = (s: string) => s.split(",").map((v) => v.trim());

/**
 * `images` replaces the screenshots exported from Notion (used for confidential projects).
 * `leadImages` are added in front of them (e.g. a newer cover image) and survive `pnpm assets`.
 */
const data: (Omit<Project, "images"> & { images?: ImageAsset[]; leadImages?: ImageAsset[] })[] = [
  {
    slug: "ui-code-ai",
    summary: "사내에 축적된 디자인 데이터로 자체 학습한 모델이 디자인을 크로스 플랫폼 컴포넌트 코드로 변환하도록 돕는 AI 시스템",
    punchline: ["디자인 데이터에서", "크로스 플랫폼 코드로"],
    name: "UI 코드 자동화 AI 시스템",
    // Confidential (current employer): model names, training pipeline and screenshots are intentionally omitted.
    client: "스튜디오씨드코리아",
    duty: "Development Team Leader",
    keywords: list("Design-to-Code, AI Pipeline, Cross-platform"),
    notionDate: { start: "2026-06-01" },
    fullName:
      "AI 기반 코드 생성 시스템 (AI-assisted Design-to-Code System for Cross-platform Components)",
    domain: "스튜디오씨드코리아 / Design & Interaction data",
    period: "2026.01 -",
    tasks: [
      "디자인 데이터를 크로스 플랫폼 컴포넌트 코드로 변환·생성하는 AI 시스템 전체 설계 및 개발 리드",
      "AI 엔지니어 및 앱 개발자로 구성된 4~5명 애자일 팀 운영",
      "사내에 축적된 디자인 데이터를 학습 데이터로 정제하는 데이터·학습 파이프라인 설계",
      "룰 기반 모듈과 AI 모델 단계를 결합한 코드 생성 파이프라인 설계 (직접 주도)",
      "이미지 기반·레이아웃(구조) 기반 입력의 코드 변환을 보조하는 모델 자체 학습 (AI 엔지니어와 협업)",
      "AOS·iOS·Web 크로스 플랫폼 컴포넌트 코드 생성 파이프라인 구축",
    ],
    roles: ["Development Team Leader", "(+ Product Owner, + AI Engineer)"],
    skills: list("Python, PyTorch, Computer Vision, LLM, AI Pipeline, AWS, Git, Figma, Notion"),
    images: [{ src: "/projects/ui-code-ai/overview.svg", width: 1200, height: 675 }],
    caseStudy: {
      problem:
        "범용 LLM만으로는 디자인의 구조(계층·반복 요소)를 안정적으로 읽기 어려워, 생성된 코드가 화면 단위로 평평하게 나오고 재사용하기 어려웠습니다.",
      decisions: [
        "룰 기반 모듈 사이사이에 AI 모델 단계를 배치한 코드 생성 파이프라인을 직접 설계",
        "이미지 기반 입력과 레이아웃(구조) 기반 입력을 모두 코드로 변환할 수 있도록 변환 경로를 설계",
        "사내에 축적된 디자인 데이터로 이미지·레이아웃(구조)을 이해하는 보조 모델을 팀과 함께 자체 학습해 파이프라인에 연결하고, AOS·iOS·Web 컴포넌트 코드로 출력",
      ],
      outcome: {
        label: "관찰된 효과",
        text: "반복되는 UI 요소를 묶어 재사용하기 쉬운 컴포넌트 단위로 코드를 그룹화·구성하는 데 도움을 주었습니다.",
        note: "내부 사례 기준의 정성적 관찰입니다.",
      },
    },
  },
  {
    slug: "alan",
    summary: "검색에서 LLM으로 옮겨가는 사용자를 위한 검색 스타일 LLM Agent 서비스 — 특화 에이전트 개발과 유료 전환",
    punchline: ["검색처럼 쓰는", "LLM Agent 서비스"],
    // Slide generation feature (led from research/planning). Sidebar with personal history cropped out.
    leadImages: [{ src: "/projects/alan/cover.webp", width: 1920, height: 1145 }],
    name: "Alan LLM service",
    client: "이스트소프트",
    duty: "Product Owner",
    keywords: list("PO, PMO, System Architect, Development Leader"),
    notionDate: { start: "2025-04-22" },
    fullName: "Alan (LLM based Agentic AI Search Engine Service)",
    domain: "이스트소프트/ LLM 기반 AI 서비스",
    period: "2025.04 -",
    tasks: [
      "LLM 기반의 Agentic AI 앱 서비스 개발 파트 리드하며 Product Owner 업무 수행",
      "AI 연구원 및 앱 개발자(FE, BE)로 구성된 파트 리드",
      "Dev, QA, Stage, Release 서버 분리하여 운영, 관리",
      "Azure, Fast API, React, LangGraph 구조 아키텍처링",
      "패치 노트 페이지 운영, 관리",
      "품질 테스트 및 사내 타 부서 (QA, 인증, 결제, 인프라 등) 개발/품질/인프라 팀과 협업",
      "LLM 기반 AI 앱 서비스 기능 기획, 일정, 리스크 관리",
      "이미지 서치, 유튜브 서치·요약, 보고서 생성, 슬라이드 생성 기능과 특화 에이전트 독자 개발",
      "슬라이드 생성 기능: 조사·기획 단계부터 프로젝트 주도",
      "딥리서치·슬라이드 생성 서비스 배포, Pro 구독 서비스 런칭",
      "백오피스 내부 운영 툴 개발",
      "결제 시스템 프로세스 및 상품 유료화 정책 수립",
      "상용화 운영 중 ([https://myalan.ai/](https://myalan.ai/))",
    ],
    roles: ["Product Owner", "(+ Project Manager, + Development Leader)"],
    caseStudy: {
      problem:
        "사용자들이 검색 사이트에서 LLM 서비스로 옮겨가는 흐름 속에서, 검색에 익숙한 사용자도 자연스럽게 쓸 수 있는 LLM Agent 서비스가 필요했습니다.",
      decisions: [
        "LLM Agent 서비스를 검색 스타일로 제공해 기존 검색 사용자의 진입 장벽을 낮춤",
        "이미지 서치, 유튜브 서치·요약, 보고서 생성, 슬라이드 생성 등 기능과 특화 에이전트를 독자 개발",
        "슬라이드 생성 기능은 조사·기획 단계부터 프로젝트를 주도",
        "무료 서비스를 유료로 전환하며 다양한 사용자층을 고려한 결제 프로세스와 유료화 정책 수립",
      ],
      outcome: {
        label: "결과",
        text: "딥리서치·슬라이드 생성 서비스를 배포하고 Pro 구독을 런칭해 무료 서비스를 유료 상용 서비스로 전환했으며, 운영을 위한 백오피스 내부 툴까지 개발했습니다. ([myalan.ai](https://myalan.ai/))",
      },
    },
    skills: list("GPT, Gemini, MCP, Notion, Google Analytics, Git, Azure, Figma, MS Docs, Slashpage"),
  },
  {
    slug: "mx-studio",
    summary: "3D Web Component 제작 소프트웨어 (사내 주력 제품)",
    punchline: ["3D Web Component", "제작 소프트웨어"],
    name: "MX Studio",
    client: "티맥스메타에이아이",
    duty: "Project Leader",
    keywords: list("Web, 3D, React, Spring, Cloud"),
    notionDate: { start: "2022-07-01", end: "2025-02-28" },
    fullName: "MX studio",
    domain: "티맥스메타에이아이/3D소프트웨어",
    period: "2022.07 - 2025.02",
    tasks: [
      "3D Web Component 제작 소프트웨어 'MX studio' 개발에 참여",
      "System Engineer, Project Manager로서 설계 및 개발 업무 수행",
      "기획, 디자이너, 개발자, QA로 구성된 TF팀 리드",
      "3D 물체의 이벤트와 액션 기능 설계/개발 리드",
      "물리 엔진과 실시간 랜더링 및 후처리 기능 설계/개발 리드",
      "Node 기반의 visual code system 설계/개발 리드",
      "외부 Beta test 진행 중 ([https://www.mxstudio.store/](https://www.mxstudio.store/))",
    ],
    roles: ["System Engineer, Project Manager"],
    skills: list("Docker, Git, JavaScript, TypeScript, 3D 그래픽, Java, AWS, Notion, Figma"),
    caseStudy: {
      problem:
        "3D 웹 콘텐츠를 만들 때마다 개발자가 3D 엔진 코드를 직접 작성해야 해서 제작 비용이 크고, 비개발자는 참여하기 어려웠습니다.",
      decisions: [
        "노드 기반 노코드 인터랙션(비주얼 코드 시스템)으로 개발자 없이 3D 이벤트·액션을 제작하도록 설계",
        "물리 엔진·실시간 렌더링·후처리를 엔진 수준에서 제공하고, 3D 템플릿·데이터 연동형 모델·3D 공간 내 2D 콘텐츠 연동 지원",
        "기획·디자인·개발·QA로 구성된 TF팀 리드",
      ],
      outcome: {
        label: "결과",
        text: "MX Studio의 3D 웹 컴포넌트 산출물로 [닥터메타](/projects/dr-meta)와 [Meta.CRO](/projects/meta-cro) 웹앱을 개발했고, 외부 베타 테스트를 진행했습니다.",
      },
    },
  },
  {
    slug: "dr-meta",
    summary: "MX Studio의 3D 컴포넌트 산출물로 개발한 전국 암센터 활용 메타버스 플랫폼",
    name: "닥터메타",
    client: "한국스마트헬스케어협회",
    duty: "Project Leader",
    keywords: list("Web, 3D, Healthcare, React, Spring, Cloud"),
    notionDate: { start: "2024-06-01", end: "2025-01-31" },
    fullName: "닥터메타",
    domain: "한국스마트헬스케어협회/헬스케어",
    period: "2024.06 - 2025.01",
    tasks: [
      "암센터 의료진과 환자를 위한 메타버스 플랫폼 '닥터메타' 프로젝트에 참여",
      "책임자로서 설계 및 개발 PM/PE 업무 수행",
      "기획, 디자이너, 개발자, QA로 구성된 TF팀 리드",
      "[MX Studio](/projects/mx-studio)로 제작한 3D 웹 컴포넌트 산출물을 활용해 웹앱 개발",
      "React 기반의 웹 앱과 Unity 앱 연동 설계/개발 리드",
      "관리자 페이지 및 권한 기능 설계/개발 리드",
      "내부 Beta test 진행 중 ([https://healthcare.drmeta.kr/](https://healthcare.drmeta.kr/), [https://web.drmeta.kr/](https://web.drmeta.kr/))",
    ],
    roles: ["System Engineer, Project Manager"],
    skills: list("Docker, Git, HTML, JavaScript, TypeScript, AWS, Unity"),
  },
  {
    slug: "meta-cro",
    summary: "MX Studio의 3D 컴포넌트 산출물로 개발한 의료 전문가 교육 플랫폼",
    name: "Meta CRO",
    client: "한국스마트헬스케어협회",
    duty: "Project Leader",
    keywords: list("Web, 3D, Healthcare, React, Spring, Cloud"),
    notionDate: { start: "2023-06-01", end: "2025-01-31" },
    fullName: "Meta.CRO",
    domain: "한국스마트헬스케어협회/헬스케어",
    period: "2023.06 - 2025.01",
    tasks: [
      "의료 전문가 교육 플랫폼 'M.CRO' 프로젝트에 참여",
      "연구책임자로서 설계 및 개발 PM/PE 업무 수행",
      "개발자, QA로 구성된 TF팀 리드",
      "[MX Studio](/projects/mx-studio)로 제작한 3D 웹 컴포넌트 산출물을 활용해 웹앱 개발",
      "3D render engine library 설계/배포 (private npm 환경 구성)",
      "상용화 운영 중 (https://www.crotraining.store/)",
    ],
    roles: ["System Engineer, Project Manager"],
    skills: list("Docker, Git, HTML, JavaScript, TypeScript, AWS"),
  },
  {
    slug: "nenoonn",
    summary: "React · React Native 크로스플랫폼 콘택트렌즈 온라인 마켓 플랫폼",
    name: "내눈N",
    client: "픽셀로",
    duty: "Project Leader",
    keywords: list("Mobile, Commerce, React, Spring, Cloud"),
    notionDate: { start: "2024-03-01", end: "2024-09-15" },
    fullName: "내눈N",
    domain: "픽셀로/커머스",
    period: "2024.03 - 2024.09",
    tasks: [
      "콘택트렌즈 온라인 마켓 플랫폼 '내눈N' 프로젝트에 참여",
      "책임자로서 설계 및 개발 PM/PE 업무 수행",
      "개발자, QA로 구성된 TF팀 리드",
      "React, React Native를 활용하여 core 소스 하나로 크로스플랫폼 앱 설계/개발 리드",
      "Android, IOS 심사에 맞게 빌드 및 배포 리드",
      "상용화 운영 중 (https://nenoonn.mycafe24.com/)",
    ],
    roles: ["System Engineer, Project Manager"],
    skills: list("Docker, Git, HTML, JavaScript, TypeScript, Java, AWS, Android, IOS"),
  },
  {
    slug: "gis-s-dcis",
    summary: "GIS 기반 삼성 데이터 센터 정보 시스템",
    name: "GIS S-DCIS",
    client: "삼성물산",
    duty: "Project Leader",
    keywords: list("Web, GIS, System, Massive data, React, Spring, Cloud"),
    notionDate: { start: "2023-12-01", end: "2024-08-15" },
    fullName: "GIS S-DCIS",
    domain: "삼성물산/건설",
    period: "2023.12 - 2024.08",
    tasks: [
      "GIS 기반 삼성 데이터 센터 정보 시스템 'GIS S-DCIS' 개발 프로젝트에 참여",
      "개발 TF팀 리드하며 개발 PM 업무 수행",
      "기획팀, 사업팀, 타사 연구팀과 소통 및 협업",
      "GeoServer와 PostGIS를 활용한 공간함수 서버 및 DB 구축",
      "GIS 데이터 기반의 map platform 구성을 위한 Openlayers 오픈소스 기술 연구",
      "공공 데이터 활용 및 정책 이슈 핸들링",
      "폐쇄망 소스 이관 및 On-Premise 환경 구축 시 생기는 이슈 트러블슈팅",
    ],
    roles: ["System Engineer, Project Manager"],
    skills: list("Docker, Git, HTML, JavaScript, TypeScript, Java, AWS"),
  },
  {
    slug: "mvs",
    summary: "멀티플레이를 위한 실시간 다중 접속 싱크 서버 연구",
    name: "MVS (Metaverse Server)",
    client: "티맥스메타에이아이",
    duty: "Project Leader",
    keywords: list("C++, Server Engine, Synchronization, Cloud"),
    notionDate: { start: "2023-01-02", end: "2024-09-15" },
    fullName: "MVS (Metaverse Server)",
    domain: "티맥스메타에이아이/Server engine",
    period: "2023.01 - 2024.09",
    tasks: [
      "멀티플레이를 위한 실시간 다중 접속 싱크 서버 연구",
      "R&D 팀 리드하며 C++ 기반의 서버 엔진 기술 연구 및 개발",
      "Client Library 설계 (Javascript, C#)",
      "서비스 플로우 설계",
    ],
    roles: ["Project Manager"],
    skills: list("Docker, Git, C++, AWS, Javascript, C#"),
  },
  {
    slug: "scon",
    summary: "블록체인 기반의 스마트 컨트렉트 플랫폼 연구",
    name: "Scon (Smart Contract)",
    client: "티맥스메타에이아이",
    duty: "Project Leader",
    keywords: list("Blockchain, Web3, React, Spring"),
    notionDate: { start: "2023-06-01", end: "2024-06-15" },
    fullName: "Scon (Smart Contract)",
    domain: "티맥스메타에이아이/Server engine",
    period: "2023.01 - 2024.09",
    tasks: [
      "블록체인 기반의 스마트 컨트렉트 플랫폼 연구",
      "R&D 팀 리드하며 이더리움, Web3j 등 기술 연구 및 개발",
      "Web 기반 Prototype 기획",
      "서비스 플로우 설계",
    ],
    roles: ["Project Manager"],
    skills: list("Git, JavaScript, Java"),
  },
];

export const projects: Project[] = data.map(({ leadImages = [], ...p }) => ({
  ...p,
  images: p.images ?? [...leadImages, ...(projectImages[p.slug] ?? [])],
}));
