// Converts the raw Notion export (notion-export/files) into web-ready assets under public/.
// Screenshots -> WebP, PDFs copied with URL-safe names. Mapping lives in notion-assets.config.json.
// Usage: pnpm assets
import { mkdir, copyFile, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "notion-export/files");
const PUBLIC = path.join(ROOT, "public");

const config = JSON.parse(await readFile(path.join(import.meta.dirname, "notion-assets.config.json"), "utf8"));

const manifest = JSON.parse(await readFile(path.join(ROOT, "notion-export/assets_manifest.json"), "utf8"));
const projectImages = {};

for (const { group, file } of manifest) {
  const slug = config.projectPages[group];
  if (!slug || config.privateProjects.includes(slug)) continue;
  const index = file.match(/_(\d+)\.\w+$/)[1];
  if (config.excludedImages?.[slug]?.includes(index)) continue;
  const outDir = path.join(PUBLIC, "projects", slug);
  await mkdir(outDir, { recursive: true });
  const out = path.join(outDir, `${index}.webp`);
  const info = await sharp(path.join(SRC, file))
    .resize({ width: config.screenshot.maxWidth, withoutEnlargement: true })
    .webp({ quality: config.screenshot.quality })
    .toFile(out);
  (projectImages[slug] ??= []).push({
    src: `/projects/${slug}/${index}.webp`,
    width: info.width,
    height: info.height,
  });
}

await mkdir(path.join(PUBLIC, "images"), { recursive: true });
const profile = await sharp(path.join(SRC, config.profilePhoto))
  .webp({ quality: 90 })
  .toFile(path.join(PUBLIC, "images/profile.webp"));
await copyFile(path.join(SRC, config.socialPreview), path.join(ROOT, "src/app/opengraph-image.png"));
for (const icon of config.icons) {
  await copyFile(path.join(SRC, icon), path.join(PUBLIC, "images", icon));
}

await mkdir(path.join(PUBLIC, "docs"), { recursive: true });
for (const [from, to] of Object.entries(config.documents)) {
  // Edited copies (e.g. redacted resume) live only in public/ — never replace them with the raw export.
  if (config.editedDocuments.includes(to)) continue;
  await copyFile(path.join(SRC, from), path.join(PUBLIC, "docs", to));
}

for (const list of Object.values(projectImages)) list.sort((a, b) => a.src.localeCompare(b.src));
const generated = `// Generated by scripts/prepare-assets.mjs — do not edit by hand.
export const profileImage = ${JSON.stringify({ src: "/images/profile.webp", width: profile.width, height: profile.height })} as const;

export const projectImages: Record<string, { src: string; width: number; height: number }[]> = ${JSON.stringify(projectImages, null, 2)};
`;
await writeFile(path.join(ROOT, "src/content/images.generated.ts"), generated);

const total = Object.values(projectImages).reduce((n, l) => n + l.length, 0);
console.log(`projects: ${Object.keys(projectImages).length}, screenshots: ${total}, documents: ${Object.keys(config.documents).length}`);
